
#include "zippies/config/ZippyPathConfig.h"

#define DEFAULT_PATH_OFFSET_X                              120.0
#define DEFAULT_PATH_OFFSET_Y                             1050.0
#define DEFAULT_TIME_FACTOR                                250

ZippyWaypoint zippyPath[]
{
    { DEFAULT_PATH_OFFSET_X+   0.0, DEFAULT_PATH_OFFSET_Y+   0.0,    0.0, DEFAULT_TIME_FACTOR* 4 },
    { DEFAULT_PATH_OFFSET_X+ 200.0, DEFAULT_PATH_OFFSET_Y+ 200.0,   90.0, DEFAULT_TIME_FACTOR* 4 },
    { DEFAULT_PATH_OFFSET_X+ 400.0, DEFAULT_PATH_OFFSET_Y+   0.0,  180.0, DEFAULT_TIME_FACTOR* 4 },
    { DEFAULT_PATH_OFFSET_X+ 200.0, DEFAULT_PATH_OFFSET_Y -200.0,  -90.0, DEFAULT_TIME_FACTOR* 8 },
    { DEFAULT_PATH_OFFSET_X -200.0, DEFAULT_PATH_OFFSET_Y+ 200.0,  -90.0, DEFAULT_TIME_FACTOR* 4 },
    { DEFAULT_PATH_OFFSET_X -400.0, DEFAULT_PATH_OFFSET_Y+   0.0,  180.0, DEFAULT_TIME_FACTOR* 4 },
    { DEFAULT_PATH_OFFSET_X -200.0, DEFAULT_PATH_OFFSET_Y -200.0,   90.0, DEFAULT_TIME_FACTOR* 8 },
    { DEFAULT_PATH_OFFSET_X+ 200.0, DEFAULT_PATH_OFFSET_Y+ 200.0,   90.0, DEFAULT_TIME_FACTOR* 8 },
    { DEFAULT_PATH_OFFSET_X+ 200.0, DEFAULT_PATH_OFFSET_Y -200.0,  -90.0, DEFAULT_TIME_FACTOR* 8 },
    { DEFAULT_PATH_OFFSET_X -200.0, DEFAULT_PATH_OFFSET_Y+ 200.0,  -90.0, DEFAULT_TIME_FACTOR* 8 },
    { DEFAULT_PATH_OFFSET_X -200.0, DEFAULT_PATH_OFFSET_Y -200.0,   90.0, DEFAULT_TIME_FACTOR* 4 },
    { DEFAULT_PATH_OFFSET_X+   0.0, DEFAULT_PATH_OFFSET_Y+   0.0,    0.0 },
};

const int zippyPathCount = sizeof(zippyPath) / sizeof(ZippyWaypoint);
